### ISSUE TITLE
getWebSocketsToken() throwing/rejecting with Error: ["EAPI:Invalid nonce"]

### ISSUE THREAD

**Issue by roberttaylortech** [jpcx/node-kraken-api#5]
Awesome strongly typed lib, Justin... thanks for this.  :) Getting this Error when calling getWebSocketsToken() (line 10 in the image).  Had been seeing the same with some other REST calls I'd tried as well. My work around has been to use [https://www.npmjs.com/package/kraken-api )](https://www.npmjs.com/package/kraken-api ) to get the token (and other REST calls) and then provide that token to node-kraken-api private websocket connection. Privates work like a champ after that!  

Is there something I'm missing that I need to do? Nonce window for my Kraken API keys is set to 0. Tips?

`(node:16640) UnhandledPromiseRejectionWarning: Error: ["EAPI:Invalid nonce"]
    at _UTF8Receiver.finalize (E:\slab\dev\kraken-ws-rt-work\node_modules\node-kraken-api\index.js:915:31)
    at IncomingMessage.<anonymous> (E:\slab\dev\kraken-ws-rt-work\node_modules\node-kraken-api\index.js:1081:29`

![node-kraken-api-nonce-issue1](https://user-images.githubusercontent.com/2290379/144763211-06557432-d8c6-41ec-9578-acca01b51d68.png)
)

**Comment by jpcx** [comment]
Hey thanks Robert, no problem! Sorry to hear that you're having nonce issues.

I opted to use plain millisecond time for the nonce generation, as seen here:
```
export const _GENNONCE = (() => {
  let prev = -1;
  let next = -1;
  return Object.freeze(() => {
    next = Date.now();
    if (next <= prev) next = prev + 1;
    prev = next;
    return next;
  });
})();
```

kraken-api, on the other hand, uses a spoofed microsecond time:
`params.nonce = new Date() * 1000; // spoof microsecond`

Since each API key nonce must always increase, using kraken-api and my client with the same key will lead to this problem. 

This can be solved by constructing your instance with a custom nonce generator (it is set to _GENNONCE by default):
`const krakenWsP = new Kraken({key:defaultKey2, secret: defaultSecret2, gennonce: () => Date.now() * 1000});`

Another thing to keep in mind is that the client allows for simultaneous REST requests, so if you plan on making more requests and you don't want to wait for each call to resolve before sending the next, increase your nonce window.

Thanks for bringing this up! I've added a note to the README for the next version :).
