### ISSUE TITLE
staking asset does not require a method param

### ISSUE THREAD

**Issue by DylanAlberto** [jpcx/node-kraken-api#7]
Hi bro, i was trying to use the stake function, but it has a required param called "method", i was searching in to Kraken API documentation but i didn't find something about it.
I think in an older version it was required but now i tried removing it from the required params and it worked.

**Comment by jpcx** [comment]
Hello, thanks for raising an issue. Hmm, it's still listed as required in the [documentation](https://docs.kraken.com/rest/#operation/stake). It might work to just specify the asset, but I suppose they require method in case there will be more than one method for a given asset in the future (right now I only see one method per asset; via `stakingAssets()`).

Have you tried adding the associated method to your query? I'll make it optional if specifying the method breaks things, but otherwise I'll keep it in line with the documentation.

**Comment by jpcx** [comment]
Closing; I just tried staking using the method name and it worked. Will keep the required property to remain in-line with the official documentation.
